"""Explicit training pipeline (never runs automatically):

    generate simulator data -> (optional) add labelled Phase 8 learning records -> chronological split
    -> RandomForest fit -> evaluate on the held-out LAST part in time -> persist a NEW version

The split is by time (no shuffling): the model is trained on earlier samples and tested on later ones, and
every sample is an independent simulated run, so no run appears on both sides. Evaluation numbers come from
the held-out simulator data only and describe how well the model separates simulator scenarios; they are
not real-world detection rates and are labelled that way in the metadata.
"""

import time
from datetime import datetime, timezone
from typing import Any

from app.agents.monitor.config import MonitorConfig
from app.ml.config import MLConfig
from app.ml.dataset import BASE_TIME, Sample, generate_dataset
from app.ml.features import FEATURE_NAMES, FEATURE_VERSION, to_vector
from app.ml.store import ModelStore

LIMITATIONS = [
    "The dataset is generated by the project's simulator; labels are the generating scenario, not real incidents.",
    "Metrics measure separation of simulator scenarios on a held-out chronological test set, not real-world accuracy.",
    "Scenario event types differ strongly between classes, so high scores are expected on this data.",
    "The test set is small; treat the numbers as indicative, not as a performance guarantee.",
]


def evaluate(y_true: list[str], y_pred: list[str], labels: list[str], benign: str) -> dict[str, Any]:
    """Accuracy, per-class and averaged precision/recall/F1, confusion matrix and benign-vs-threat errors."""
    from sklearn.metrics import accuracy_score, confusion_matrix, precision_recall_fscore_support

    p, r, f, support = precision_recall_fscore_support(y_true, y_pred, labels=labels, zero_division=0)
    macro = precision_recall_fscore_support(y_true, y_pred, labels=labels, average="macro", zero_division=0)
    weighted = precision_recall_fscore_support(y_true, y_pred, labels=labels, average="weighted", zero_division=0)
    fp = sum(1 for t, q in zip(y_true, y_pred) if t == benign and q != benign)  # benign flagged as a threat
    fn = sum(1 for t, q in zip(y_true, y_pred) if t != benign and q == benign)  # a threat called benign
    tp = sum(1 for t, q in zip(y_true, y_pred) if t != benign and q != benign)
    tn = sum(1 for t, q in zip(y_true, y_pred) if t == benign and q == benign)
    prec = tp / (tp + fp) if tp + fp else 0.0
    rec = tp / (tp + fn) if tp + fn else 0.0
    return {
        "accuracy": round(float(accuracy_score(y_true, y_pred)), 4),
        "macro": {"precision": round(float(macro[0]), 4), "recall": round(float(macro[1]), 4), "f1": round(float(macro[2]), 4)},
        "weighted": {"precision": round(float(weighted[0]), 4), "recall": round(float(weighted[1]), 4), "f1": round(float(weighted[2]), 4)},
        "per_class": {label: {"precision": round(float(p[i]), 4), "recall": round(float(r[i]), 4), "f1": round(float(f[i]), 4),
                              "support": int(support[i])} for i, label in enumerate(labels)},
        "confusion_matrix": {"labels": labels, "matrix": confusion_matrix(y_true, y_pred, labels=labels).tolist()},
        "threat_detection": {"true_positives": tp, "true_negatives": tn, "false_positives": fp, "false_negatives": fn,
                             "precision": round(prec, 4), "recall": round(rec, 4),
                             "f1": round(2 * prec * rec / (prec + rec), 4) if prec + rec else 0.0},
        "test_samples": len(y_true),
    }


def train_model(config: MLConfig, monitor: MonitorConfig, store: ModelStore, *, learning_samples: list[Sample] | None = None,
                activate: bool = False, seed: int | None = None, samples_per_class: int | None = None) -> dict[str, Any]:
    """Train and persist a NEW model version. Returns its metadata. The active model changes only if
    `activate` is true."""
    from sklearn.ensemble import RandomForestClassifier

    started = time.time()
    seed = config.dataset.seed if seed is None else seed
    data = generate_dataset(config, monitor, seed=seed, samples_per_class=samples_per_class)  # chronological
    cut = max(1, min(len(data) - 1, int(round(len(data) * (1.0 - config.dataset.test_fraction)))))
    train, test = data[:cut], data[cut:]
    if train and test and max(s.time for s in train) > min(s.time for s in test):
        raise RuntimeError("chronological split violated")  # guard against leakage
    extra = list(learning_samples or [])  # newest feedback: training only, never in the test set
    fit_set = train + extra
    labels = list(config.model.labels)
    model = RandomForestClassifier(
        n_estimators=config.model.n_estimators, max_depth=config.model.max_depth,
        min_samples_leaf=config.model.min_samples_leaf, random_state=config.model.random_state or seed,
        class_weight="balanced_subsample", n_jobs=1)
    model.fit([to_vector(s.features) for s in fit_set], [s.label for s in fit_set])
    predicted = list(model.predict([to_vector(s.features) for s in test]))
    metrics = evaluate([s.label for s in test], predicted, labels, config.model.benign_label)
    importances = sorted(zip(FEATURE_NAMES, model.feature_importances_), key=lambda x: -x[1])
    import sklearn

    metadata = {
        "model_version": store.next_version(), "model_type": "RandomForestClassifier", "framework": f"scikit-learn {sklearn.__version__}",
        "training_timestamp": datetime.now(timezone.utc).isoformat(), "training_seconds": round(time.time() - started, 2),
        "feature_version": FEATURE_VERSION, "feature_names": list(FEATURE_NAMES), "classes": list(model.classes_),
        "benign_label": config.model.benign_label, "seed": seed,
        "dataset_size": {"total": len(data) + len(extra), "train": len(fit_set), "test": len(test),
                         "simulator_generated": len(data), "learning_records": len(extra)},
        "split": {"method": "chronological", "train_until": train[-1].time.isoformat(), "test_from": test[0].time.isoformat(),
                  "base_time": BASE_TIME.isoformat()},
        "data_source": "simulator-generated (synthetic)", "evaluation_scope": "held-out simulator data only, not real-world",
        "hyperparameters": {"n_estimators": config.model.n_estimators, "max_depth": config.model.max_depth,
                            "min_samples_leaf": config.model.min_samples_leaf, "class_weight": "balanced_subsample"},
        "metrics": metrics,
        "feature_importances": [{"name": n, "importance": round(float(v), 5)} for n, v in importances[:15]],
        "limitations": LIMITATIONS, "active": False,
    }
    if extra:
        metadata["limitations"] = LIMITATIONS + [
            f"{len(extra)} labelled Phase 8 learning record(s) were added to the TRAINING set only."]
    saved = store.save(model, metadata)
    if activate:
        store.set_active(saved["model_version"])
        saved["active"] = True
    return saved
